### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by marvinstuart** [alsliahona/gcode-optimizer#1]
I am getting a errors messag MSVCP120.dll is missing from your computer

Windows 8.1

**Comment by alsliahona** [comment]
I've updated the binaries.  They are now statically linked to the CRT.  This should resolve the problem.

**Comment by marvinstuart** [comment]
It works perfectly, 

although i am using cmd prompt would it be possble to create a simple GUI to choose upload file and then the same file that has been optimized then is saved to the save directory with the file remaned a with _optimized 

by the way this is AWESOME as the know makercam has the WORSE tool path .. 

again thank you
